### ISSUE TITLE
Add app launcher icon and name

### ISSUE THREAD

**Issue by alexcmgit** [zaaii/my_comic#2]
The app is still using the Flutter default icon:

![image](https://user-images.githubusercontent.com/51419598/222183714-f9045695-416c-4725-b88b-f6d8e7188007.png)

I downloaded the apk from the drive page (from the README.md docs): https://drive.google.com/file/d/1eI_nVBU0SGnOQxCPpnBwG5lWmrXauTgc/view.

---

We can use this package: https://pub.dev/packages/flutter_launcher_icons to generate the android launcher icons.

Can you send me an icon that you would like to use as app launcher icon?

**Comment by zaaii** [comment]
I don't have an icon yet, you can add yours :)
